### ISSUE TITLE
v3 plan

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1004]
Most likely includes lots of devops work but handling this here on `market`. All still WIP.

Main Goals:

- keep the currently published assets and their liquidity alive as much as possible
- keep current `market.oceanprotocol.com` environment until v4 launch day
- provide a user flow for publishers/liquidity providers to migrate from v3 to v4

## Endpoint Changes

Unless stated otherwise, `→` means the underlying instance is available under the new given URL, while the initial URLs become the new default v4 ones with new v4 instances under the hood. Undecided on the actual URL scheme, we could also prefix everything with `v3`, like `v3.market.ocean.oceanprotocol.com`?

#### public testing phase

  - [x] setup `v4` → `v4.market.oceanprotocol.com`
- [x] in UI, both the v3 market and v4 market get a dropdown for the version number beside the app title for easy switching between above domains
- [x] split up deployments by creating new projects `market-v3` in Vercel, make it deploy the `v3` branch and PRs against it
- [x] create `v3.market.oceanprotocol.com`, deploy `v3` branch to it
- [x] switch default branch to `v4`
- [x] ~~ocean.js v3 track `v0.xx.x` needs a release with the below mentioned endpoints and v3 contract addresses for everything in `ConfigHelper`~~
- [x] sync decided on networks below with the network selector list in `app.config.js` in `v3` market branch
- [x] implement v4 migration into `v3` branch, handled in #1023
- [x] remove all publishing functionality from v3 code base, handled in  #1451
- [x] release all the v3 codebase changes to existing live market, handled in #1456

More tasks regarding v3 codebase are in the milestone https://github.com/oceanprotocol/market/milestone/10

#### live production phase

  - [x] setup `v3` → `v3.market.oceanprotocol.com`
  - [x] `v4` → `market.oceanprotocol.com`
- [x] implement redirects for all v3 assets in v4 code base, handled in #1446
- [x] rename `main` → `v3`, rename `v4`→ `main`

### Purgatory

- do we need to do something with https://github.com/oceanprotocol/market-purgatory and `market-purgatory.oceanprotocol.com` endpoint?

### Backend

We will keep all existing URLs as the v3 URLs and introduce a new versioning schema for all newly deployed v4 components.

#### v3

We should double check usage for each network and if we decide to kick out a network because of non-usage, then we can also remove it from the `market` network selector. I think `ropsten`, `mumbai`, `moonbeamalpha`, `celoalfajores` are good candidates to kick out. Or we decide to only keep mainnets, so only `mainnet`, `polygon`, `bsc`, `energyweb`. Most likely `gaiaxtestnet` needs to stay as the deltaDAO demonstrators use this.

List should be updated based on our decisions on which ones to keep. Strikethrough meaning this is going to be removed.

- `aquarius.oceanprotocol.com`
- `subgraph.mainnet.oceanprotocol.com`
- `provider.mainnet.oceanprotocol.com`
- `subgraph.ropsten.oceanprotocol.com`
- `provider.ropsten.oceanprotocol.com`
- `subgraph.rinkeby.oceanprotocol.com`
- `provider.rinkeby.oceanprotocol.com`
- `subgraph.polygon.oceanprotocol.com`
- `provider.polygon.oceanprotocol.com`
- `subgraph.moonbase.oceanprotocol.com`
- `provider.moonbase.oceanprotocol.com`
- `subgraph.moonriver.oceanprotocol.com`
- `provider.moonriver.oceanprotocol.com`
- `subgraph.gaiaxtestnet.oceanprotocol.com`
- `provider.gaiaxtestnet.oceanprotocol.com`
- ~~`subgraph.mumbai.oceanprotocol.com`~~
- ~~`provider.mumbai.oceanprotocol.com`~~
- `subgraph.bsc.oceanprotocol.com`
- `provider.bsc.oceanprotocol.com`
- `subgraph.energyweb.oceanprotocol.com`
- `provider.energyweb.oceanprotocol.com`
- ~~`subgraph.celoalfajores.oceanprotocol.com`~~
- ~~`provider.celoalfajores.oceanprotocol.com`~~

#### v4

Checkbox refers to endpoints have been created and deployed.

- [x] `v4.aquarius.oceanprotocol.com`
- [x] `v4.subgraph.mainnet.oceanprotocol.com`
- [x] `v4.provider.mainnet.oceanprotocol.com`
- [x] `v4.subgraph.ropsten.oceanprotocol.com`
- [x] `v4.provider.ropsten.oceanprotocol.com`
- [x] `v4.subgraph.rinkeby.oceanprotocol.com`
- [x] `v4.provider.rinkeby.oceanprotocol.com`
- [x] `v4.subgraph.polygon.oceanprotocol.com`
- [x] `v4.provider.polygon.oceanprotocol.com`
- [x] `v4.subgraph.moonbase.oceanprotocol.com`
- [x] `v4.provider.moonbase.oceanprotocol.com`
- [x] `v4.subgraph.moonriver.oceanprotocol.com`
- [x] `v4.provider.moonriver.oceanprotocol.com`
- [ ] `v4.subgraph.gaiaxtestnet.oceanprotocol.com`
- [ ] `v4.provider.gaiaxtestnet.oceanprotocol.com`
- [x] `v4.subgraph.mumbai.oceanprotocol.com`
- [x] `v4.provider.mumbai.oceanprotocol.com`
- [x] `v4.subgraph.bsc.oceanprotocol.com`
- [x] `v4.provider.bsc.oceanprotocol.com`
- [x] `v4.subgraph.energyweb.oceanprotocol.com`
- [x] `v4.provider.energyweb.oceanprotocol.com`
- [ ] `v4.subgraph.celoalfajores.oceanprotocol.com`
- [ ] `v4.provider.celoalfajores.oceanprotocol.com`

_Developing..._

**Comment by alexcos20** [comment]
adding @md00ux

**Comment by TimDaub** [comment]
hey these renames to domain names are not backwards compatible and will break the entire ecosystem. Instead of renaming aquarius.oceanprotocol.com → aquarius.v3.oceanprotocol.com I think you should do the other way around. Otherwise all applications will stop working once you do this type of change.

**Comment by alexcos20** [comment]
I agree that once we have a plan, we should communicate it, so apps can prepare an update.
And after we execute it, communicate again so all apps can update their endpoints.

Examples:
- If you call now an infura endpoint, can you send a transaction without EIP changes? No, you cannot, because the underlying backend has changed in order to keep up with updates
- If you visit gmail.com, are you going to get the web interface of gmail v1? or the latest ?

**Comment by TimDaub** [comment]
I don't doubt the necessity of bumping a major version to signal a breaking change but please let's keep these selective examples at a minimum as Windows 10 can today be upgraded from MSDOS 30 years ago.

You've made a choice to collect as many changes as you can in a version bump. You could have shipped features in minor versions and then collected breaking changes in a major version. But it didn't happen. Me and others now have to face a wall of changes that completely overwhelms you and you didn't talk to us about it anytime in the past.

Whether you manage to justify it to yourself or not: third-party apps will be broken and the people that pay the greatest cost are those that have the highest stakes, you included.

**Comment by kremalicious** [comment]
These endpoints are all operated by OPF and were created to run in conjunction with the market frontend. If you depend on some specific version of some endpoint or even run a business on top, I would highly suggest running your own endpoints of provider or aquarius. As you know each asset publisher should actually run their own provider. Those above endpoints are made public for convenience, testing, prototyping, not for use in everybody's production app and we never said that we will keep them backwards compatible in any way. Agree this is not ideal and proper API versioning would be way better solution, but the reality is we do not have enough resources to maintain multiple different codebases for each component, with drastic conceptional and breaking changes in between, like new DDO, or NFTs.

And by not versioning the current endpoints we created the dilemma that we have to change the current ones too, as keeping v3 under the "default" domains like `aquarius.oceanprotocol.com` would create confusion too and unnecessarily gives the old stuff more prominence.

We definitely will use `market.oceanprotocol.com` for accessing the v4 version of market. If we want to use versioning for the other endpoints though, then introducing this now is actually good time. But to reduce the confusion about the short default current endpoints, we would have to give them up, and redirect them, just like in my above list. But then again, 3rd parties can choose to quickly change the endpoint their apps are using and with that can delay any updates.

> I don't doubt the necessity of bumping a major version
"v3", "v4" etc. were always marketing versions, not semantic versioning. I don't like it either but it has become the de facto standard in the decentralized space, where this is usually based on new major contract versions, see Uniswap v3 or Balancer v2

> Honestly it seems like the major version was bumped and then the changes rolled in. 
have you seen the multiple roadmap update blog posts? The v4 milestones and all their issues on each repo?

**Comment by TimDaub** [comment]
> If you depend on some specific version of some endpoint or even run a business on top, I would highly suggest running your own endpoints of provider or aquarius

- Yes, I have made that decision time ago to not rely on Aquarius anymore as semversioning wasn't consistently applied there and there were numerous other problems https://rugpullindex.com/changelog#September052021
- Consider that not everybody can run an Aquarius node as e.g. some Aquarius operators are forced to use the "encryption" flag since in the design it has been conflated with "access": https://github.com/oceanprotocol/market/issues/643#issuecomment-855630968





> And by not versioning the current endpoints we created the dilemma that we have to change the current ones too, as keeping v3 under the "default" domains like `aquarius.oceanprotocol.com` would create confusion too and unnecessarily gives the old stuff more prominence.

Honestly, I think it's worse that you now double down on sticking to an upgrade pattern that's breaking everyone's apps at a major version bump. If e.g. you'd accepted the inconsistencies and mistakes you made until v3 and from now on versioned by adding rather than replacing that issue would be gone. E.g. v3 stays aquarius.oceanprotocol.com and v4 is v4.aquarius.oceanprotocol.com, v5.aquarius.oceanprotocol.com. 

Nobody asks you to maintain multiple code bases. All you'd have to do is add more servers to the v4 domains in the upgrade. You leave v3 running and announce a shut-down date e.g. half a year later. E.g. there'd be no need to maintain the v3 servers. You could just let them run.

> But then again, 3rd parties can choose to quickly change the endpoint their apps are using and with that can delay any updates.

I mean my initial complain just surfaced in the TLD backward-compatability being broken. But e.g. the reasons why now the DID is created from the checksum of a sha hash is beyond me.
It's entirely unnecessary to update the DID. I've said that for multichain, including the chain id is necessary as CREATE2 may allow creating two token contracts with the same address on different chains. The DID V4 isn't addressing the problem, but creates an entirely new one. E.g. with didv3 you can go back and forth between token address and did. With V4 you can't and so entire applications may have to be rewritten if that assumption had been made.



> Not sure I can follow, there are multiple roadmap blog posts, each component on GitHub has their own v4 milestone with dedicated issues, and all have a `v4` branch those issues are worked into.

You said it yourself. v3, v4 are marketing versions and that's my problem. You're using a marketing process to make software engineering decisions and that's why everything is all over the place these days. 

If everyone would have just done their thing then Ocean now had many different updates represented as major and minor semversion bumps.

We wouldn't have to fight about v3, v4... Already that a whole codebases transitions to v4 makes no sense. 

Every repository is different and runs theoretically on its own timeline with semversioning. Sure, you can e.g. create the version x for the contracts and that tickles down to e.g. an API endpoint. But e.g. it wouldn't necessarily mean that you had to bump the major version of an API endpoint if you changed the underlying contract.

So the fact that the marketing process gives everyone a get-out-of-jail-card for shipping v4 creates the chaos and makes people downstream that have to deal with this mess unhappy.

**Comment by kremalicious** [comment]
Issue finally sparked internal discussions too and we found more reasons to just suck it up and to keep the existing URLs as the v3 URLs. I updated the description with that.

/cc @alexcos20 @md00ux

**Comment by kremalicious** [comment]
Plan executed
