### ISSUE TITLE
Remove AMM pools functionality

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1607]
As we are moving away from the dynamic pricing schema, we need to remove everything POOL related.

- [x] #1614 Remove AMM related code (UI)
- [x] #1614 Remove AMM related code (cleanup)
- [x] #1614 Remove tests
- [x] #1610 Update READMEs (docs)

**Comment by AnaLoznianu** [comment]
yes

**Comment by EnzoVezzaro** [comment]
Hi @AnaLoznianu ,

I'm working on removing as much code related to pools as I can without compromising the assets with dynamic pricing. In the meanwhile I'd like to ask you some more questions: 

- "Highest liquidity" in homepage needs to change, right? 

![Screenshot 2022-07-21 at 08 50 11](https://user-images.githubusercontent.com/13741335/180218012-f9513f07-46a4-4961-b6b5-2c10bcecc01d.png)

- in Profile we need to:
  - remove "Liquidity in Own Assets" and "Liquidity", should we change it with something else?

![Screenshot 2022-07-21 at 08 49 43](https://user-images.githubusercontent.com/13741335/180218164-4be747b9-692b-45fe-b716-ec6829a284cd.png)

  - remove "Pool shares" and "Pool transactions" tabs

![Screenshot 2022-07-21 at 08 49 59](https://user-images.githubusercontent.com/13741335/180218212-08347ffe-6cc8-4a48-93e6-9fcb1c75bf6a.png)

So far we've removed the dynamic pricing on publish and the pool / trade tabs in asset details.

**Comment by EnzoVezzaro** [comment]
@AnaLoznianu What about the banner? I think we need to remove "One-sided Stacking", What should we say instead?

![Screenshot 2022-07-27 at 07 07 04](https://user-images.githubusercontent.com/13741335/181232853-948b0fd2-46f3-4f4f-a7a5-5f80eed3c24c.png)

**Comment by AnaLoznianu** [comment]
Great point @EnzoVezzaro! IMHO we can keep just Explore OceanONDA V4 and the blogpost link

**Comment by EnzoVezzaro** [comment]
Sure? There's a lot of white space around it, the container looks kind of empty. But we can do it:

![Screenshot 2022-07-27 at 07 17 03](https://user-images.githubusercontent.com/13741335/181234286-a889dabf-a27c-47ef-b5e1-5a1299ae3fb9.png)
