### ISSUE TITLE
In Ocean Market, owner can list / unlist assets

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#1747]
**Summary**

- Problem: active assets are discoverable in Ocean Market, even if owner doesn't want to list them.
- Solution: In Ocean Market, owner can list / unlist assets. Eg via candidate solution (2) or (3) below.

**Motivation**

- Submissions from the first predict-ETH challenge show up in Ocean Market. [Here](https://market.oceanprotocol.com/asset/did:op:ec7fd49888469f10e234af498ec8e06a44881d48effdc6d284d6107586d6609d). Wed expected this; that's how Ocean is designed by default. However we don't want this to happen.
- To generalize, one can imagine many flows where someone publishes an asset in Ocean, but they don't want it to be listed / discoverable in Ocean Market or other public markets. 
- Or, they've published it in Ocean Market, and want to keep it active but don't want it discoverable anymore. 

**Candidate solutions**
1. In the predict-eth README, don't publish the ddo. Just the data NFT & datatoken (including url service), and not the asset. 
2. Leverage [erc721.state](https://docs.oceanprotocol.com/core-concepts/did-ddo#state). Any asset with state >= 1 isn't displayed in Ocean Market.
3. Have another parameter in [`ddo.metadata`](https://docs.oceanprotocol.com/core-concepts/did-ddo#metadata): `listInMarkets` (a simple boolean). Use this appropriately in Ocean Market.

**Analysis: candidate 1**

Candidate 1 solves the first issue listed above, not the other two. It _is_ useful, however, so it will be done via [ocean.py#1022](https://github.com/oceanprotocol/ocean.py/issues/1022).

**Analysis: candidate 2**

We already have [erc721.state](https://docs.oceanprotocol.com/core-concepts/did-ddo#state). Any asset with state >=1 will not be displayed in the market.

Here are the possible states:
![states](https://user-images.githubusercontent.com/5305452/196504009-e6f12ef2-7509-428a-a9db-00f416fda9d1.png)

Q: which state should the asset be, to not display? It's still **active**, after all (state 0). 

A: The question is N/A. "state" is orthogonal to "list y/n". So we need a different field.

**Analysis & details: candidate 3**

> 3. Have another parameter in [`ddo.metadata`](https://docs.oceanprotocol.com/core-concepts/did-ddo#metadata): `listInMarkets` (a simple boolean). Use this appropriately in Ocean Market.

This solves all three issues.

**Precise specs for solution:**

- Have another field in ddo.metadata: `"listInMarkets" : true | false`.
- In Market's browse/search results, it filters out assets having showInMarkets = False. Exception: when asset owner is logged in, the hidden assets will not be filtered, and will have an affordance so they know it's hidden.
- Market still shows the asset page to anyone, when direct url is given. (The asset isn't "listed" per se, but people can still look at it.)
- In Ocean Market, inside "edit ddo" page, there will be a new entry "show/hide" that can be toggled, which set the value for "listInMarkets".
- All of the behavior above is independent of "state" field

**TODOs:**
- [ ] In aquarius, support "precise specs" above as appropriate
- [ ] In market, ""
- [ ] In docs, document as appropriate
- [ ] Re-deploy components as needed

Background: [slack message](https://oceanprotocol.slack.com/archives/C047QMC1Z4G/p1666107788337639) that led to this.

**Comment by mihaisc** [comment]
> Have another field in ddo.metadata: "listInMarkets" : true | false.

This is in aqua , ocean.js/py

> In Market's browse/search results, it filters out assets having showInMarkets = False. Exception: when asset owner is logged in, the hidden assets will not be filtered, and will have an affordance so they know it's hidden.

We will show them in their profile page (only for them)

Also, this doesn't solve much realistically, a market doesn't need to respect this "rule", we can't enforce it.

**Comment by AnaLoznianu** [comment]
@alexcos20 ---> "asset unlisted" sounds better :D 
@trentmc If we are doing this, then through the predict README the user needs to publish the DDO also to benefit from this functionality.

**Comment by trentmc** [comment]
>> [Trent] Have another field in ddo.metadata: "listInMarkets" : true | false.

> [Mihai] This is in aqua , ocean.js/py

Interesting. If that's the case we don't need to add it, or expand on `state`. Could you show me where please? I don't see it in https://docs.oceanprotocol.com/core-concepts/did-ddo

And, if it isn't there, I'm fine to go with Alex's suggestion of another possible value for `state`. (I'd still prefer something orthogonal to state, but, whatever:)

----

> [Mihai] Also, this doesn't solve much realistically, a market doesn't need to respect this "rule", we can't enforce it.

Simply not true. Realistically, Ocean Market + Daimler are the only markets out there right now. And we can choose to respect this rule for Ocean Market.

----

> [Ana] If we are doing this, then through the predict README the user needs to publish the DDO also to benefit from this functionality.

The predict-eth README already publishes the DDO, via `OceanAssets::create_url_asset()`. That's the way the problem emerged, since the asset showed up in the market, yet wasn't wanted there (yet was "active"). First bullet in "motivation" at top. To prevent future predict-eth assets showing up, we can make it where ddo specifies "hide" using the new functionality of this issue, or not to add the ddo. For predict-eth, the latter is cleaner, I'll do it in [ocean.py#1022]( https://github.com/oceanprotocol/ocean.py/issues/1022).

**Comment by kremalicious** [comment]
> That's the way the problem emerged, since the asset showed up in the market, yet wasn't wanted there

What problem? You tell people to spam the production networks because I don't know why, then we add a functionality so those people can hide their assets? Afterwards. And we hope publishers will do this. The real solution is to publish those assets on test networks if there is no value in them.

As we have no user request for this feature, fine adding another state to NFT as we did, but would suggest not adding any new UI for this, as we also don't have any UI for all the other states.

**Comment by mihaisc** [comment]
state 5  Unlisted in markets. 
Already updated ocean.js, pr in market has been ready for some time.

**Comment by AnaLoznianu** [comment]
Ocean.py linked issue: https://github.com/oceanprotocol/ocean.py/issues/1027
Docs linked issue: https://github.com/oceanprotocol/docs/issues/1141
