### ISSUE TITLE
[EPIC] Publisher credibility

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#190]
- [ ] ENS domain display instead of account when detected (#188)
- [ ] publisher/owner search (#187)
- [ ] official partners list (#189)
- [ ] community-maintained verified list
- [ ] ...
