### ISSUE TITLE
[Sub-EPIC] Positive-label lists (Pledged, Data launch partner, etc)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#228]
General idea: Support the following labels:
- `"pledged"` -- pledged to not sell DTs for OCEAN, to not stake way more DTs in the pool, and to not rug pull; pledged to only remove 1% per week. Gave contact information that has been verified.
- `"data launch partner"` -- one of the 8ish partners that launched with Ocean. (Do *not* grow this list). At some point, remove this label completely.
- `"publicly traded"` -- is a publicly-traded company that must follow public-company rules and has reputational skin-in-the-game
- (And do *not* have any stamp-of-approval lists like "data partners" or "verified".)

Tasks:
- [ ] Write policy for positive-label lists. [Issue.](https://github.com/oceanprotocol/list-datapartners/issues/4)
- [ ] Implement SW for positive-label lists. [Issue.](https://github.com/oceanprotocol/list-datapartners/issues/6)
- [ ] Fill positive-label lists. [Issue.](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/list-datapartners/3)

**Comment by kremalicious** [comment]
who is this multi-repo epic now managed in market? Is market now the multi-repo-issue? This all becomes really noise where there should be only 1 issue in repo or 1 epic and 1 issue in 2 repos, becomes 4 issues across 3 repos, why?

**Comment by trentmc** [comment]
There are 3 separate tasks do be done roughly 3 separate groups of people: write the policy, implement the sw, populate the lists. 

At first I had all three in the rug pull epic, but that became hard to manage. So I created its own epic. 

Which issue belongs to which repo (market, multi, etc) is still a bit messy. Please transfer issues as you see fit.

**Comment by trentmc** [comment]
We've already shipped 'data partners list'. This epic was written as a possible evolution of that. We've discussed more internally. [Market-234](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/234) is a new GitHub issue for future directions.

Therefore *this* issue is obsolete. Closing.
