### ISSUE TITLE
[Sub-EPIC] Purgatory list (IP violations etc)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#229]
General idea: Support the following labels: Asset Purgatory, Asset Disabled, Actor Purgatory, Actor Disabled. The process by which an asset or actor goes from one label to another is described in the 'policy' doc. It's for things like IP violation, publishing sensitive data, and rug pulls.

**[Policies here](https://github.com/oceanprotocol/list-purgatory/tree/main/policies).**

Tasks:
- [ ] Write policy for purgatory [MultiRepo-35](https://github.com/oceanprotocol/multi-repo-issue/issues/35)
- [ ] Implement SW for purgatory [Market-208](https://github.com/oceanprotocol/market/issues/208)
- [ ] Fill initial purgatory lists [Market-225](https://github.com/oceanprotocol/market/issues/225)

**Comment by kremalicious** [comment]
closing since it's redundant. For `market`, there should be only 1 issue describing the actual implementation, which we doing not have yet. But we can use #208 for it
