### ISSUE TITLE
[EPIC] that price thing

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#35]
Figure out the best UI to get the values needed for publishing:

### Battle plan

- [x] new UI for fixed price
- [x] new UI for dynamic price
- [x] new price form widget
- [x] dynamic price: collect and pass correct values to publish method
- [x] output price on asset details page
- [x] output price in asset teasers
- [x] fixed price: wait for new fixed contract, and addition to lib-js
- [x] fixed price: collect and pass correct values to publish method
- [x] visual distinction between fixed/dynamic price on Price output
- [x] output price in asset preview during publish
- [x] fix price display when user is not connected to correct network (should get fixed with https://github.com/oceanprotocol/market/pull/51)
- [x] figure out UI for liquidity/pool infos/providing liquidity/removing liquidity
- [x] output all possible fees during asset creation

### User Stories

1. As a _publisher_ I want to receive 10 OCEAN when someone downloads my data set.
2. As a _publisher_ I want to receive 10 OCEAN when someone runs a compute job on my data set.
...

### Ideas

- Should we have a distinction between **Use (Download/Compute)** & **Trade**, like we prepared for asset details already?
- create data token for each data set?
- have user decide on data token ticker name?
