### ISSUE TITLE
Ocean Market supports $OCEAN-backed stablecoin

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#447]
**Motivations**

- Main: For stakers, reduce risk exposure to fluctuations in $OCEAN itself
- Also: Fewer variables for a user to have to consider when engaging with Ocean Market
 
**TODOs for this issue**

- [ ] An $OCEAN-backed _perpetual_ stablecoin is deployed to Eth mainnet (with 3rd party collaborators). Note: can't use ODollar as it's non-perpetual
- [ ] Stablecoin is bridged to Polygon, including good documentation / low-friction app for users
- [ ] In Polygon, create a pool to easily swap to the stablecoin (from mETH or other). Add liquidity so slippage is low.
- [ ] Ensure completed elsewhere: [Market#468](https://github.com/oceanprotocol/market/issues/468) "Market code can support different base token". 
- [ ] Ensure completed elsewhere: [Market#467](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/467) "Ocean Market supports >1 market per datatoken"
- [ ] Have Ocean Market base token = stablecoin, in both Eth mainnet and Polygon. It would still need to support OCEAN in older pools (possible to have both due to market 467 work above)

**Comment by kremalicious** [comment]
> either (a) build support for: users can create pools that have OCEAN or stablecoin, or (b) switch everything over to stablecoin

this needs to be defined first, before doing #468. Otherwise #468 has to support both options but in end we might decide only on one. Every _or_ in a spec leads to building multiple conditional flows.

**Comment by trentmc** [comment]
> this needs to be defined first
Good point. I added a new bullet to the checklist: to decide:) 

And I also added another new bullet to the checklist: do #468 first. 

We can postpone doing the decision bullet until #468 is done.

**Comment by kremalicious** [comment]
There is no "$OCEAN-backed stablecoin" so this issue seems impossible to solve in itself so closing for now until there is such a stablecoin. Linked issues are more valid as they prepare app for using any token in the end

**Comment by trentmc** [comment]
This issue is an epic, as part of the roadmap. We link to it from elsewhere, to be able to track it.

The end result of this epic is that Ocean Market supports an OCEAN backed stablecoin.

This epic has several sub tasks, including the deploying the stablecoin itself.

The issue should remain open.

**Comment by kremalicious** [comment]
epics do not belong on the market repo if they concern more than the market repo, as they skew the measured progress of frontend team. Most tasks in here should not be done by frontend, and those which should have already their own issues where #468 then needs a more precise definition of the defaults which can then be the stablecoin so that issue also solves "Have Ocean Market base token = stablecoin"

So marked this as an epic and I would suggest moving it to multi-repo-issues
