### ISSUE TITLE
Revised menubar

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#577]
Quick wins:

- [x] make it full width, visually separated from rest of page, more space allows for more menu items and possible new multi-network buttons in the future (done in #672)
- [ ] add a search icon/search bar, solving all those space issues we run into on search page e.g. in #548. #665
- [x] visually deal with better with overflow pattern, a scrollbar should never appear (done in #672)
- [x] consistent style of menu items & actions (include mobile as well) (done in #672)

**Comment by kremalicious** [comment]
closing as most of the tasks mentioned were done in #672 in `feature/multinetwork`, and the remaining one is tracked in #665
