### ISSUE TITLE
Add custom provider endpoint during publish

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#75]
In Ocean Market, OPF has to run Provider and therefore holds the data service decryption key. This means that OPF has custody of these keys.

What to do for this issue: 
- [ ]  In Ocean Market, give an option for the user to provide an endpoint of the Provider. Therefore the user can run their own Provider, and retain decentralization. We can expect enterprises and others to do this. Handled in https://github.com/oceanprotocol/market/issues/702
- [ ]  In Ocean Market, if the user chooses to use the OPF-run Provider, have a GUI affordance to set the expectation that this Provider will only be run until some specific cut-off date: Dec 31, 2021. This ensures that OPF is not bound to some weird long-term commitment that it didn't mean to make. Handled in https://github.com/oceanprotocol/market/issues/703
- [x] Allow external provider in ocean-lib-js [Issue](https://app.zenhub.com/workspaces/ocean-v30-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean-lib-js/278)
- [x] Allow external provider in ocean-lib-py [Issue](https://app.zenhub.com/workspaces/ocean-v30-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean-lib-py/49)

Note: in the future we will want more decentralized storage of private keys. See [related tech spike](https://app.zenhub.com/workspaces/ocean-v30-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/tech-spikes/99).

Note: moved from [this issue](https://app.zenhub.com/workspaces/ocean-v30-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/18)

**Comment by kremalicious** [comment]
This is of course more tricky in implementation and there's some discussion going on in the PR to find the best compromise https://github.com/oceanprotocol/market/pull/364#issuecomment-773133718

**Comment by kremalicious** [comment]
superseded by #702
